.github/ISSUE_TEMPLATE/feature_request.md

I created an issue template for future issues.
More details : #1

feat: template issue

---

.github/workflows/mirror.yml

I created the mirroring yml to merge this repository on the Epitechs'one.
More details: #3

feat(workflow): mirroring action

---

.gitignore
CMakeLists.txt
Client/CMakeLists.txt
Client/src/main.cpp
README.md
Server/CMakeLists.txt
Server/src/main.cpp

I configured the CMakeLists.txt to compile the client/server on Linux.
To compile the project, look at the readme section "How to build ? (Linux)"
More details : #9

FEAT: cmake create binaries

---

Contributing.md

To obtains more details, please see:
- #5

FEAT: contributing file

---

README.md

This benchmark target the libraries SFML, SDL, Raylib, Irrlicht and Ogre3D.
Here the link of the Wiki : [SlimWiki](https://slimwiki.com/6fvu0f5pu/getting-started-nqdxve9qg-/welcome)
>[!IMPORTANT]
>Please read the benchmark before accept this PR.

DOCS: benchmark for graphical library

---

README.md

To have more information please see:
- #8

DOCS: Add the team logo in readme.

---

.github/workflows/cmake.yml
Client/CMakeLists.txt
Ecs/CMakeLists.txt
Server/CMakeLists.txt

This pull request introduces a new GitHub Actions workflow file named cmake.yml to automate the build process for our project using CMake. The workflow is triggered on check_run, push, and pull_request events.
It supports multiple operating systems including Ubuntu, Windows, and macOS. 
Key Features:  
- Checkout Project: Uses actions/checkout@v4 to checkout the project repository.
- Build Project: Utilizes threeal/cmake-action@v2.0.0 to build the project using CMake.
This addition ensures that our project is built and tested across different environments, improving the reliability and portability of our codebase.

FEAT: GitHub Actions workflow for CMake build

---

.github/workflows/cmake-linux.yml
.github/workflows/cmake-windows.yml
README.md

I split cmake.yml to have the check on one file by os.
To have the option to have a compilation badge in our readme.

FEAT: CICD cross os check

---

Ecs/src/Registry.cpp
Ecs/src/Registry.hpp
Ecs/src/SparseArray.hpp
Server/CMakeLists.txt
Server/include/IComponent.hpp
Server/include/ISystem.hpp
Server/src/GameEngine/DLLoader/DLLoader.hpp

I created the DLLoader to load components and systems .so files and added the folder Server/lib to store components and systems.
I fix some issues for SparseArray and Register to store shared_pointers.
Finally, I implemented the IComponent and ISystem classes to handle components and systems with the DLLoader.
Here the tutorials to create components : https://slimwiki.com/6fvu0f5pu/getting-started-nqdxve9qg-/ecs-component-w9on3dn-o-mi3jl3gpofei
And to create systems: https://slimwiki.com/6fvu0f5pu/getting-started-nqdxve9qg-/ecs-system-oyzc-3tlv-toxcperq4hri
More details : #20

FEAT: dlloader class

---

.gitignore
Client/Interface/I2dEntities.hpp
Client/Interface/I3dEntities.hpp
Client/Interface/IColor.hpp
Client/Interface/IFont.hpp
Client/Interface/IGraphic.hpp
Client/Interface/IMusic.hpp
Client/Interface/IShader.hpp
Client/Interface/ISound.hpp
Client/Interface/IText.hpp
Client/Interface/ITexture.hpp
Client/Interface/KeyMap.hpp

This pull request adds extensive documentation to various interfaces and enums across the project.
The documentation includes:
- **Class-level descriptions**
- **Method-level descriptions**
- **Parameter details**
---
- **Class Documentation**: `IFont` interface.
- **Documented Methods**: `GetFontDefault`, `LoadFont`.
---
- **Class Documentation**: `ISound` interface.
- **Documented Methods**:  
`LoadSound`, `IsSoundReady`, `UpdateSound`, `UnloadSound`, `PlaySound`, `StopSound`,  
`SetSoundVolume`, `GetSoundVolume`, `SetSoundPitch`, `GetSoundPitch`,  
`SetSoundLoop`, `GetSoundLoop`.
---
- **Class Documentation**: `IMusic` interface.
- **Documented Methods**:  
`LoadMusic`, `IsMusicReady`, `PlayMusic`, `StopMusic`, `UnloadMusic`,  
`SetMusicVolume`, `GetMusicVolume`, `SetMusicPitch`, …

FEAT: All Interfaces for the graphic side

---

Server/CMakeLists.txt
Server/src/GameEngine/Application/Application.cpp
Server/src/GameEngine/Application/Application.hpp
Server/src/main.cpp

I created the Application class.
For the moment, this class run nothing, but in the future, its goal is to handle the totality of the GameEngine.

35 feat create the main class of server

---

Engine/Client/CMakeLists.txt
Engine/Client/Src/Component/FontPathComponent.cpp
Engine/Client/Src/Component/FontPathComponent.hpp
Engine/Client/Src/Component/MaterialMapComponent.cpp
Engine/Client/Src/Component/MaterialMapComponent.hpp
Engine/Client/Src/Component/MusicPathComponent.cpp
Engine/Client/Src/Component/MusicPathComponent.hpp
Engine/Client/Src/Component/MusicPitchComponent.cpp
Engine/Client/Src/Component/MusicPitchComponent.hpp
Engine/Client/Src/Component/MusicVolumeComponent.cpp
Engine/Client/Src/Component/MusicVolumeComponent.hpp
Engine/Client/Src/Component/ObjPathComponent.cpp
Engine/Client/Src/Component/ObjPathComponent.hpp
Engine/Client/Src/Component/SoundPathComponent.cpp
Engine/Client/Src/Component/SoundPathComponent.hpp
Engine/Client/Src/Component/SoundPitchComponent.cpp
Engine/Client/Src/Component/SoundPitchComponent.hpp
Engine/Client/Src/Component/SoundVolumeComponent.cpp
Engine/Client/Src/Component/SoundVolumeComponent.hpp
Engine/Client/Src/Component/TexturePathComponent.cpp
Engine/Client/Src/Component/TexturePathComponent.hpp

This pull request introduces several new components to handle sound and music functionalities within the graphical engine.
- **Header**: `Engine/Client/Src/Component/MusicPathComponent.hpp`
- **Source**: `Engine/Client/Src/Component/MusicPathComponent.cpp`
- **Description**: Manages the path to a music file.
- **Header**: `Engine/Client/Src/Component/SoundPathComponent.hpp`
- **Source**: `Engine/Client/Src/Component/SoundPathComponent.cpp`
- **Description**: Manages the path to a sound file.
- **Header**: `Engine/Client/Src/Component/SoundVolumeComponent.hpp`
- **Source**: `Engine/Client/Src/Component/SoundVolumeComponent.cpp`
- **Description**: Manages the volume of a sound file.
- **Header**: `Engine/Client/Src/Component/MusicVolumeComponent.hpp`
- **Source**: …

FEAT: Create sound music components

---

Engine/Server/Config/Scenes/firstScene.json
Engine/Shared/Ecs/Src/Registry.cpp
Engine/Shared/Ecs/Src/Registry.hpp
Engine/Shared/Interface/ISystem.hpp
Engine/Shared/SceneManager/ASceneManager.cpp
Engine/Shared/SceneManager/ASceneManager.hpp
Engine/Shared/SceneManager/ISceneManager.hpp
R-TypeGame/Systems/MoveSystem.hpp

I've changed the prototype of system to include an int who represente the index of player who sent entities.

REFACTOR: Prototype System

---

Engine/Client/CMakeLists.txt
Engine/Client/Src/Application/Application.cpp
Engine/Client/Src/Application/Application.hpp
Engine/Client/Src/Systems/DrawOBJ/DrawOBJSystem.cpp
Engine/Client/Src/Systems/DrawTexture/DrawTextureSystem.cpp
Engine/Client/Src/Systems/DrawTexture/DrawTextureSystem.hpp
Engine/Shared/Interface/IGraphic.hpp
GraphicLibrary/Src/GraphicLib.cpp
GraphicLibrary/Src/GraphicLib.hpp

I created the system DrawTexture in default graphics system.
I also created a method drawTexture in IGraphic to draw 2D sprites on the screen using the graphical lib .so.

FEAT: Create system draw texture

---

Engine/Client/Src/ClientSceneManager/ClientSceneManager.hpp
Engine/Client/Src/GetGraphicalLibrary/GetGraphicalLibrary.hpp
Engine/Server/Src/GameEngine/ServerSceneManager/ServerSceneManager.hpp
Game/GameData/Scenes/firstScene.json
R-TypeGame/Systems/Players/PlayerInitSystem.cpp

I fixed the new path of config files and systems, since @Peralban created a Game folder.

fix(Path): New path for config files

---

Engine/Client/CMakeLists.txt
Engine/Client/Src/Application/Application.cpp
Engine/Client/Src/Application/Application.hpp
Engine/Client/Src/Systems/SpriteSheetAnimation/SpriteSheetAnimationSystem.cpp
Engine/Client/Src/Systems/SpriteSheetAnimation/SpriteSheetAnimationSystem.hpp
Engine/Server/CMakeLists.txt
Engine/Shared/Component/SpriteSheetAnimationComponent.cpp
Engine/Shared/Component/SpriteSheetAnimationComponent.hpp
Engine/Shared/Component/TextComponent.hpp
Engine/Shared/SceneManager/ASceneManager.cpp
Engine/Shared/SceneManager/ASceneManager.hpp
Game/GameData/Entities/PlayerOne.json
R-TypeGame/Parser/LifeParser/LifeParser.cpp
R-TypeGame/Parser/PlayerParser/PlayerParser.cpp
R-TypeGame/Parser/Position2DParser/Position2DParser.cpp
R-TypeGame/Parser/ScaleParser/ScaleParser.cpp
R-TypeGame/Parser/SpeedParser/SpeedParser.cpp
R-TypeGame/Parser/SpriteSheetAnimationParser/SpriteSheetAnimationParser.cpp
R-TypeGame/Parser/SpriteSheetAnimationParser/SpriteSheetAnimationParser.hpp
R-TypeGame/Parser/TextureRectParser/TextureRectParser.cpp
R-TypeGame/Systems/CMakeLists.txt
R-TypeGame/Systems/Players/PlayerInitOneSystem.cpp

I added the possibility to create animations with 2D textures.
Your entities can know have a SpriteSheetAnimationComponent to handle animations.
For animations you have to set:
- Number of sprite sheet frames.
- Time for each frame.
- Vector direction x to change Texture Rect left.
- Vector direction y to change Texture Rect top.
- Position x of the first frame.
- Position y of the first frame.
- reverseMod to true if frames should be played in both directions. (For example: left to right and right to left).

FEAT: Create animation component and system

---

Engine/Server/Src/GameEngine/Application/Application.cpp

I launched the game in the server. (Yes just that)

FEAT: Link the game systems with server.

---

Engine/Client/Src/Network/NetworkClient.cpp
Engine/Server/Src/GameEngine/Application/Application.cpp
Engine/Server/Src/Network/NetworkServer.cpp
Game/GameData/Entities/PlayerFour.json
Game/GameData/Entities/PlayerThree.json
Game/GameData/Entities/PlayerTwo.json

I've fixed all segfault about the PlayerComponent check.

Fix: Segfault PlayerComponent

---

Game/GameData/Scenes/firstScene.json
R-TypeGame/Systems/Background/PlanetRestartSystem.cpp
R-TypeGame/Systems/Background/PlanetRestartSystem.hpp
R-TypeGame/Systems/Background/UpdatePlanet.cpp
R-TypeGame/Systems/Background/UpdatePlanet.hpp
R-TypeGame/Systems/CMakeLists.txt
R-TypeGame/Systems/Hitbox/HitboxPlayerSystem.cpp
R-TypeGame/Systems/Hitbox/HitboxPlayerSystem.hpp

I handle the player collisions with asteroid, when the player hit the asteroid he lose 20 hp and is kill if his life is under 0.

FEAT: Handle player collision with asteroid

---

Engine/Client/Src/Network/NetworkClient.cpp
Engine/Server/Src/GameEngine/Application/Application.cpp
Engine/Shared/Ecs/Src/Registry.hpp
Game/GameData/Scenes/firstScene.json
R-TypeGame/SystemNetworkUpdate/CMakeLists.txt
R-TypeGame/SystemNetworkUpdate/UpdateShootSystem/updateShootSystem.cpp
R-TypeGame/SystemNetworkUpdate/UpdateShootSystem/updateShootSystem.hpp
R-TypeGame/Systems/Shoot/ShootSystem.cpp

I've send the packet from the system who create the shoot to communicate with other client !

Send packet create shoot

---

Engine/Client/CMakeLists.txt
Engine/Client/Src/Application/Application.cpp
Engine/Client/Src/Application/Application.hpp
Engine/Client/Src/InitWindow/InitWindow.cpp
Engine/Client/Src/InitWindow/InitWindow.hpp
Engine/Shared/Interface/IGraphic.hpp
Game/Config/Settings.json
GraphicLibrary/Src/GraphicLib.cpp
GraphicLibrary/Src/GraphicLib.hpp

This pull request adds the InitWindow class to the project, which is responsible for initializing the graphical window using the provided settings. The key features and changes introduced in this pull request are:  
- Initialization of Window: The InitWindow class initializes the window with the specified resolution, fullscreen mode, and title from the settings file.
- Error Handling: Proper error handling is implemented to manage issues during the parsing of the settings file.
- Resolution Management: The class sets the list of available resolutions and applies the selected resolution.
- Fullscreen Mode: The class sets the window to fullscreen mode if specified in the settings.
This addition ensures that the graphical window is correctly initialized with the desired settings, improving …

FEAT: Init window from json Methods

---

README.md

Write a complete information to know how to play in our game

REFACTOR: Complete how to play

---

R-TypeGame/Systems/CMakeLists.txt
R-TypeGame/Systems/Move/MoveSystemDown/MoveSystemDown.cpp
R-TypeGame/Systems/Move/MoveSystemDown/MoveSystemDown.hpp
R-TypeGame/Systems/Move/MoveSystemLeft/MoveSystemLeft.cpp
R-TypeGame/Systems/Move/MoveSystemRight/MoveSystemRight.cpp
R-TypeGame/Systems/Move/MoveSystemRight/MoveSystemRight.hpp
R-TypeGame/Systems/Move/MoveSystemUp/MoveSystemUp.cpp

I fix the hit boxes of the screen to not leave the area with our spaceships.

REFACTOR: Stop leaving the screen with starships

---

Engine/Client/Src/Application/Application.cpp
Engine/Client/Src/Network/NetworkClient.cpp
Engine/Client/Src/Network/NetworkClient.hpp
Engine/Client/Src/Systems/DrawOBJ/DrawOBJSystem.cpp
Engine/Client/Src/Systems/DrawText/DrawTextSystem.cpp
Engine/Client/Src/Systems/DrawTexture/DrawTextureSystem.cpp
Engine/Client/Src/Systems/DrawTextureRect/DrawTextureRectSystem.cpp
Engine/Client/Src/Systems/SpriteSheetAnimation/SpriteSheetAnimationSystem.cpp
Engine/Server/Src/GameEngine/Application/Application.cpp
Engine/Server/Src/Network/NetworkServer.cpp
Engine/Shared/Ecs/Src/Registry.hpp
R-TypeGame/SystemNetworkUpdate/UpdatePlayerConnectionSystem/updatePlayerConnectionSystem.cpp
R-TypeGame/SystemNetworkUpdate/UpdatePositionSystem/updatePositionSystem.cpp
R-TypeGame/SystemNetworkUpdate/UpdateShootSystem/updateShootSystem.cpp
R-TypeGame/Systems/Background/PlanetRestartSystem.cpp
R-TypeGame/Systems/Hitbox/HitboxPlayerSystem.cpp
R-TypeGame/Systems/Mouse/MouseSystem.cpp
R-TypeGame/Systems/Move/MoveEntities/MoveEntitiesSystem.cpp
R-TypeGame/Systems/Move/MoveSystemDown/MoveSystemDown.cpp
R-TypeGame/Systems/Move/MoveSystemLeft/MoveSystemLeft.cpp
R-TypeGame/Systems/Move/MoveSystemRight/MoveSystemRight.cpp
R-TypeGame/Systems/Move/MoveSystemUp/MoveSystemUp.cpp
R-TypeGame/Systems/MoveSystem/MoveMobs/MoveMobsSystem.cpp
R-TypeGame/Systems/Shoot/ShootDamageSystem.cpp
R-TypeGame/Systems/Shoot/ShootDestroySystem.cpp
R-TypeGame/Systems/Shoot/ShootSystem.cpp
R-TypeGame/Systems/ShootMob/ShootSystem.cpp
R-TypeGame/Systems/Typing/TypingSystem.cpp

I FINALLY fixed segfaults in Server and Clients by adding lockguards (aka mutex) in all function that modified register values.
With this fix, I hope all segfaults are FIXED.
After 1 week of work on this problem it's time to take a break an breath the pure air of mother nature.

FIX: Multithreading read and write on same vectors

---

LICENSE

Adding a MIT License for the project.

FEAT: Create LICENSE

---

Network/ABI/ABIServer.cpp
Network/ABI/ABIServer.hpp
Network/CMakeLists.txt
Network/Messages/UDPPacket/UDPPacket.cpp
Network/Messages/UDPPacket/UDPPacket.hpp
Network/Units/Server/Server.cpp
Network/Units/Server/Server.hpp

I've created the server class of ABI with associated function.

Feat: Create Server class in ABI

---

Network/ABI/ABIClient.cpp
Network/ABI/ABIClient.hpp
Network/ABI/ABINetwork.hpp
Network/ABI/ABIServer.cpp
Network/ABI/ABIServer.hpp
Network/CMakeLists.txt
Network/Messages/AMessage/AMessage.cpp
Network/Messages/AMessage/AMessage.hpp
Network/Messages/Auth/Auth.cpp
Network/Messages/Auth/Auth.hpp
Network/Messages/IMessage.hpp
Network/Units/ANetworkUnit/ANetworkUnit.cpp
Network/Units/ANetworkUnit/ANetworkUnit.hpp
Network/Units/Client/Client.hpp
Network/Units/INetworkUnit.hpp

I handle the sent of logout, login or register information (for Client).
I also created the methods to retrieves data from packets for logout, login and register (for Server).

FEAT: Login, register and logout method ABI

---

Network/ABI/ABINetwork.cpp
Network/ABI/ABINetwork.hpp
Network/CMakeLists.txt
Network/Units/ANetworkUnit/ANetworkUnit.cpp
Network/Units/ANetworkUnit/ANetworkUnit.hpp
Network/Units/INetworkUnit.hpp

I've added these function in the ABI Network !

FEAT: Create setMessageInQueue function && getMessageInQueue function

---

Network/ABI/ABIClient.cpp
Network/ABI/ABIClient.hpp
Network/ABI/ABIServer.cpp
Network/ABI/ABIServer.hpp
Network/CMakeLists.txt
Network/Messages/ChatBox/ChatBox.cpp
Network/Messages/ChatBox/ChatBox.hpp

I created the class ChatBoxMessage to handle messages from a chatbox for clients.

FEAT: Chatbox messages ABI

---

Network/ABI/ABIClient.cpp
Network/ABI/ABIClient.hpp
Network/ABI/ABIServer.cpp
Network/ABI/ABIServer.hpp
Network/CMakeLists.txt
Network/Messages/Auth/Auth.cpp
Network/Messages/IMessage.hpp
Network/Messages/KeyPressed/KeyPressed.cpp
Network/Messages/KeyPressed/KeyPressed.hpp

I created the Keypressed class to handle keys from client to server.

FEAT: Keypressed message abi

---

Engine/Client/CMakeLists.txt
Engine/Client/Src/Application/Application.cpp
Engine/Client/Src/Application/Application.hpp
Engine/Server/CMakeLists.txt
Engine/Server/Src/GameEngine/Application/Application.cpp
Engine/Server/Src/GameEngine/Application/Application.hpp
Network/ABI/ABINetwork.cpp
Network/Units/ANetworkUnit/ANetworkUnit.cpp
Network/Units/ANetworkUnit/ANetworkUnit.hpp
Network/Units/Client/Client.cpp
Network/Units/INetworkUnit.hpp
Network/Units/Server/Server.cpp
Network/Units/Server/Server.hpp

I Link the server and the client of the ABI in the project.
For the moment the project didn't work because all systems are not linked with the new ABI.

FEAT: Link the project with the ABI

---

Network/ABI/ABIClient.cpp
Network/ABI/ABIClient.hpp
Network/ABI/ABIServer.cpp
Network/ABI/ABIServer.hpp
Network/CMakeLists.txt
Network/Messages/CreateEntity/CreateEntity.cpp
Network/Messages/CreateEntity/CreateEntity.hpp
Network/Messages/UpdateComponent/UpdateComponent.cpp
Network/Messages/UpdateComponent/UpdateComponent.hpp

I've created the function to create the payload to update a component and the function to get the payload. And I've added these function in ABI CLient and Server.

FEAT: Create function to update component

---

Engine/Server/Src/GameEngine/Application/Application.cpp
Engine/Server/Src/GameEngine/Application/Application.hpp

When the server receive a key event, it call the linked system.

FEAT: Link ABI to keys systems

---

Engine/Client/CMakeLists.txt
Engine/Client/Src/Application/Application.cpp
Engine/Server/CMakeLists.txt
Engine/Shared/Consumption/ConsumptionCompute.cpp
Engine/Shared/Consumption/ConsumptionCompute.hpp
Game/Config/Settings.json

To do my compute, I've found : https://stackoverflow.com/questions/63166/how-to-determine-cpu-and-memory-consumption-from-inside-a-process
And I applied it.

Feat: Create class to compute consummation

---

R-TypeGame/Systems/Menus/Buttons/ConnectButton/ConnectButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/CreateRoomPageButton/CreateRoomPageButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/ExitButton/ExitButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/IpTextBox/IpTextBoxInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/JoinRoomPageButton/JoinRoomPageButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/LoginButton/LoginButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/LoginPageButton/LoginPageButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/MapEditorButton/MapEditorButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/MultiplayerButton/MultiplayerButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/PasswordTextBox/PasswordTextBoxInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/PortTextBox/PortTextBoxInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/RegisterButton/RegisterButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/RegisterPageButton/RegisterPageButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/SingleplayerButton/SingleplayerButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/UsernameTextBox/UsernameTextBoxInitSystem.cpp
R-TypeGame/Systems/Mouse/MouseSystem.cpp

Since it was awful to implement a new unselection behaviour for new buttons, I moved this handling to the mouse system.

REFACTOR: Move button unselection to the mouse system

---

Engine/Client/Src/Application/Application.cpp
Game/GameData/Scenes/Menus/roomCreationMenu.json
Network/ABI/ABIClient.cpp
Network/ABI/ABIClient.hpp
Network/Errors/AError.hpp
Network/Units/Client/Client.cpp
Network/Units/Client/Client.hpp
R-TypeGame/EventHandlers/CMakeLists.txt
R-TypeGame/EventHandlers/ConnectServer/ConnectServerHandler.cpp
R-TypeGame/EventHandlers/CreateRoom/CreateRoomHandler.cpp
R-TypeGame/EventHandlers/CreateRoom/CreateRoomHandler.hpp
R-TypeGame/Systems/Menus/Buttons/AreCheatsOnButton/AreCheatsOnButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/CreateRoomButton/CreateRoomButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/IsRoomPrivateButton/IsRoomPrivateButtonInitSystem.cpp

Now, we are able to create and join a room thanks to menus.
When you create a room, your are directly redirect to the room created.

FEAT: Linked create rooms buttons with ABI

---

Engine/Server/Src/GameEngine/Application/Application.cpp
Network/ABI/ABINetwork.cpp
Network/ABI/ABINetwork.hpp
Network/ABI/ABIServer.cpp
Network/ABI/ABIServer.hpp
Network/Units/ANetworkUnit/ANetworkUnit.cpp
Network/Units/ANetworkUnit/ANetworkUnit.hpp
Network/Units/Client/Client.cpp
Network/Units/Client/Client.hpp
Network/Units/INetworkUnit.hpp
Network/Units/Server/Server.cpp
Network/Units/Server/Server.hpp

I changed the way messages are sent between client and server.
The server can now decide to send a message to only one client or all of them.

REFACTOR: Send messages target to one client

---

Engine/Client/Src/Application/Application.cpp
Engine/Client/Src/Application/Application.hpp
Engine/Server/Src/GameEngine/Room/Room.cpp
Game/GameData/Scenes/firstScene.json
Network/ABI/ABIClient.cpp
Network/ABI/ABIClient.hpp
Network/ABI/ABIServer.cpp
Network/ABI/ABIServer.hpp
Network/CMakeLists.txt
Network/Messages/AssignToken/AssignToken.cpp
Network/Messages/AssignToken/AssignToken.hpp
Network/Messages/IMessage.hpp
R-TypeGame/EventHandlers/CMakeLists.txt
R-TypeGame/EventHandlers/CreateShoot/CreateShootHandler.cpp
R-TypeGame/EventHandlers/CreateShoot/CreateShootHandler.hpp
R-TypeGame/SystemNetworkUpdate/CMakeLists.txt
R-TypeGame/SystemNetworkUpdate/UpdateShootSystem/updateShootSystem.cpp
R-TypeGame/Systems/CMakeLists.txt
R-TypeGame/Systems/Shoot/ShootSystem.cpp
R-TypeGame/Systems/Shoot/ShootSystem.hpp

I've Create the RollBack system:
I've add a MessageType (AssignToken) and their associated function to send her idxENtity to the client, so that it can procces the key
And I've link the Shootsystem with ABi so now the Player can shoot.

FEAT: Create RollBAck system and Link ABI to UpdateShootSystem

---

Engine/Server/Src/GameEngine/Application/Application.cpp
Engine/Server/Src/GameEngine/Application/Application.hpp
Network/Database/Database.hpp

On the client, you can now successfuly log and register, as the server correctly answers based on the db state.
* Login functional.
* Register functional.

FEAT: link db to abi

---

Engine/Server/Src/GameEngine/Room/Room.cpp
Network/ABI/ABIServer.cpp
Network/ABI/ABIServer.hpp

I've add the send of actual game to a new client.

FEAT: Send update of game to new client

---

Engine/Client/Src/Application/Application.cpp
Engine/Shared/SceneManager/ASceneManager.cpp
Engine/Shared/SceneManager/ASceneManager.hpp
Engine/Shared/SceneManager/ISceneManager.hpp
Network/ABI/ABIClient.hpp
Network/Units/ANetworkUnit/ANetworkUnit.cpp
Network/Units/ANetworkUnit/ANetworkUnit.hpp
Network/Units/Client/Client.cpp
Network/Units/INetworkUnit.hpp
R-TypeGame/EventHandlers/CMakeLists.txt
R-TypeGame/EventHandlers/SinglePlayer/SinglePlayerHandler.cpp
R-TypeGame/EventHandlers/SinglePlayer/SinglePlayerHandler.hpp
R-TypeGame/Game/GameData/Scenes/Menus/mainMenu.json
R-TypeGame/Systems/CMakeLists.txt
R-TypeGame/Systems/Menus/Buttons/SingleplayerButton/SingleplayerButtonInitSystem.cpp
R-TypeGame/Systems/Menus/Buttons/SingleplayerButton/SingleplayerButtonInitSystem.hpp
R-TypeGame/Systems/Shoot/ShootDestroySystem.cpp
R-TypeGame/Systems/ShootMob/ShootSystem.cpp

The singlePlayer button on the main menu is now linked to an offline game.
>[!NOTE]
> I didn't create a local server for that

FEAT: Added the possibility to play in singlePlayer.

---

.gitignore
Engine/Shared/DefaultComponents/Colour/ColourComponent.hpp
Engine/Shared/DefaultComponents/IComponent.hpp
Engine/Shared/DefaultComponents/Position2D/Position2DComponent.hpp
Engine/Shared/DefaultSystems/CMakeLists.txt
Engine/Shared/DefaultSystems/LuaScript/LuaScriptSystem.cpp
Engine/Shared/DefaultSystems/LuaScript/LuaScriptSystem.hpp
R-TypeGame/Components/Shoot/ShootComponent.hpp
R-TypeGame/Game/GameData/Scenes/Menus/mainMenu.json
R-TypeGame/Game/GameData/Scripts/helloWorld.lua
R-TypeGame/Game/GameData/Scripts/rgbColour.lua
R-TypeGame/Game/GameData/Scripts/ySlide.lua
vcpkg.json

FEAT: Scripting

---

Engine/Client/Src/Application/Application.cpp
Engine/Client/Src/Application/Application.hpp
Engine/Server/Src/GameEngine/Application/Application.cpp
Engine/Server/Src/GameEngine/Application/Application.hpp
Engine/Server/Src/GameEngine/Room/Room.cpp
Engine/Server/Src/GameEngine/Room/Room.hpp
Network/ABI/ABINetwork.cpp

I multi-threaded the sending of messages to improve performances.

FEAT: Multi-thread send of messages.

---

R-TypeGame/Game/GameData/Scenes/Menus/mainMenu.json

I fixed the singlePlayer by adding the event which start the game in the mainMenu json file

FIX: Start of single player

---

.github/workflows/Release.yml
Engine/Shared/DefaultSystems/CMakeLists.txt
R-TypeGame/Game/GameData/Scenes/Menus/mainMenu.json
R-TypeGame/Game/GameData/Scripts/rgbColour.lua

Fix the load of LuaScriptSystem on windows. The .dll is failing to be loaded.

FIX: load luaScriptSystem in windows

---

Engine/Client/Src/Application/Application.cpp
Engine/Client/Src/Application/Application.hpp
Engine/Server/Src/GameEngine/Application/Application.cpp
Engine/Server/Src/GameEngine/Room/Room.cpp
Engine/Shared/DefaultSystems/MoveEntities/MoveEntitiesSystem.cpp
R-TypeGame/Systems/Move/MoveSystemDown/MoveSystemDown.cpp
R-TypeGame/Systems/Move/MoveSystemLeft/MoveSystemLeft.cpp
R-TypeGame/Systems/Move/MoveSystemRight/MoveSystemRight.cpp
R-TypeGame/Systems/Move/MoveSystemUp/MoveSystemUp.cpp

I don't know if it works, but I think.

FIX: Shoot
